name: Application Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-app:
    name: App Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: ATLAS_URI=${{ secrets.DB_URL }} npm t